// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcfwnbezcieqpcenwfbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZnduYmV6Y2llcXBjZW53ZmJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0MzIwNjEsImV4cCI6MjA3NjAwODA2MX0.UNV_roXZSvWAP1xKRAmFBKIMqheW1UB3YSyFdSNmxx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});